[build]
  publish = "build"
  command = "npm run build"

[dev]
  port = 3000

# Redirect all requests to the index.html for a single-page app (SPA)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200